"""Project details and milestone checklists for each course."""

COURSE_PROJECTS = {
    "nlp": {
        "title": "NLP Mini-Project",
        "type": "Individual/Group",
        "summary": "Choose a topic, do literature review, implement, analyze results, present and submit report.",
        "presentation": "~10 min, graded by instructor, TA, and students",
        "report_deadline": "End of Week 13 (~Apr 20)",
        "presentation_date": "2026-04-20",
        "milestones": [
            {"id": "nlp-p1", "title": "Choose project topic", "due": "2026-03-16", "done": False},
            {"id": "nlp-p2", "title": "Literature review (find 5-10 related papers)", "due": "2026-03-23", "done": False},
            {"id": "nlp-p3", "title": "Design approach / methodology", "due": "2026-03-30", "done": False},
            {"id": "nlp-p4", "title": "Set up codebase & data pipeline", "due": "2026-04-03", "done": False},
            {"id": "nlp-p5", "title": "Core implementation", "due": "2026-04-07", "done": False},
            {"id": "nlp-p6", "title": "Run experiments & collect results", "due": "2026-04-10", "done": False},
            {"id": "nlp-p7", "title": "Analyze results & write findings", "due": "2026-04-13", "done": False},
            {"id": "nlp-p8", "title": "Draft report (intro, method, results, conclusion)", "due": "2026-04-15", "done": False},
            {"id": "nlp-p9", "title": "Create presentation slides", "due": "2026-04-17", "done": False},
            {"id": "nlp-p10", "title": "Rehearse presentation", "due": "2026-04-19", "done": False},
            {"id": "nlp-p11", "title": "Present & submit final report", "due": "2026-04-20", "done": False},
        ],
        "topic_ideas": [
            "Sentiment analysis on HK social media data",
            "Text summarization with fine-tuned LLM",
            "Named entity recognition for Chinese text",
            "Question answering system using RAG",
            "Fake news detection with Transformer models",
            "Chatbot for course Q&A using LLM fine-tuning",
        ],
    },
    "cvpr": {
        "title": "CVPR Group Project",
        "type": "Group (2-3 students)",
        "summary": "Focus on one CV task (segmentation, detection, classification). Submit proposal, present, and submit report + code.",
        "presentation": "10 min/person + 5 min Q&A per group",
        "report_deadline": "2026-04-30",
        "presentation_date": "2026-04-16",
        "milestones": [
            {"id": "cvpr-p1", "title": "Form project group (2-3 students)", "due": "2026-02-19", "done": False},
            {"id": "cvpr-p2", "title": "Choose project task (segmentation/detection/classification)", "due": "2026-02-28", "done": False},
            {"id": "cvpr-p3", "title": "Research related work & find datasets", "due": "2026-03-10", "done": False},
            {"id": "cvpr-p4", "title": "Write proposal: preliminary studies & rationale", "due": "2026-03-15", "done": False},
            {"id": "cvpr-p5", "title": "Write proposal: methodology & initial design", "due": "2026-03-18", "done": False},
            {"id": "cvpr-p6", "title": "Submit proposal via Moodle (20%)", "due": "2026-03-20", "done": False},
            {"id": "cvpr-p7", "title": "Set up codebase (PyTorch + OpenCV)", "due": "2026-03-31", "done": False},
            {"id": "cvpr-p8", "title": "Implement baseline model", "due": "2026-04-04", "done": False},
            {"id": "cvpr-p9", "title": "Implement proposed method / improvements", "due": "2026-04-07", "done": False},
            {"id": "cvpr-p10", "title": "Run experiments & collect results", "due": "2026-04-09", "done": False},
            {"id": "cvpr-p11", "title": "Create presentation slides", "due": "2026-04-12", "done": False},
            {"id": "cvpr-p12", "title": "Rehearse presentation with group", "due": "2026-04-14", "done": False},
            {"id": "cvpr-p13", "title": "Present & demo (40%)", "due": "2026-04-16", "done": False},
            {"id": "cvpr-p14", "title": "Write final report", "due": "2026-04-25", "done": False},
            {"id": "cvpr-p15", "title": "Clean up code & prepare submission", "due": "2026-04-28", "done": False},
            {"id": "cvpr-p16", "title": "Submit report + PPT + code via Moodle (40%)", "due": "2026-04-30", "done": False},
        ],
        "topic_ideas": [
            "Medical image segmentation (e.g., retinal vessel, lung CT)",
            "Real-time object detection for traffic/pedestrian",
            "Image classification for food recognition",
            "Face mask detection using deep learning",
            "Scene segmentation for autonomous driving",
            "Defect detection in manufacturing",
        ],
    },
}
